name: Build Binary

on: [push, pull_request, workflow_dispatch]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Binary
      run: |
        docker build -t builder .
        docker run --rm builder dkp-pacman -Syu --noconfirm
        docker run -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@v3
      with:
        name: Time_Sync.wps
        path: "*.wps"
        if-no-files-found: error
