name: Build Binary

on: [push, pull_request, workflow_dispatch]

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    name: Build plugin
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Docker
      run: docker build --tag plugin-builder .

    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: plugin-builder
        options: --rm --volume ${{ github.workspace }}:/project
        run: |
          ./bootstrap
          ./configure --host=powerpc-eabi CXXFLAGS="-O2"
          make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Time_Sync.wps
        path: "*.wps"
        if-no-files-found: error
